Bug fix
ShangwuYao/DeepAttack pull request #2
Opened 2018-07-09 23:54 UTC by RyanTang1

Add proper error handling. Remove suggestions and rating as well

2018-07-09 23:59 UTC, dnc1994 commented on src/evaluation_worker.py
> +        model_size=os.path.getsize(model_file)
The original way is better because we don't know if `os.path.getsize` is reliable. Plus we don't need to download the files if the sizes are already violating the constraints.

2018-07-09 23:59 UTC, dnc1994 commented on src/evaluation.py
> +            result={'robustness':None,'details':[],'graph_link':None,'suggestion':None}
Remove `graph_link` and `suggestion`.

2018-07-10 00:00 UTC, dnc1994 requested changes
Request two changes.

2018-07-10 00:03 UTC, RyanTang1 commented
Removed suggestions and graphlink.
Restore the original way of checking size

2018-07-16 22:58 UTC, dnc1994 approved these changes
Looks good to me!

2018-07-16 23:06 UTC, merged